Eligible Prospects :=
DISTINCTCOUNT ( dim_prospect[prospect_id] )

Converted Prospects :=
CALCULATE ( DISTINCTCOUNT ( dim_prospect[prospect_id] ), dim_prospect[converted] = 1 )

Conversion Rate :=
DIVIDE ( [Converted Prospects], [Eligible Prospects] )

Net Revenue :=
SUM ( fct_orders[net_revenue] )

Contribution Margin :=
SUM ( fct_orders[contribution_margin] )

Contribution Margin % :=
DIVIDE ( [Contribution Margin], [Net Revenue] )

Margin Per Eligible Prospect :=
DIVIDE ( [Contribution Margin], [Eligible Prospects] )

On-Time Delivery Rate :=
AVERAGE ( fct_deliveries[on_time] )

